//! Raw bindings, generated by `build.rs` from the vendor `toupcam.h`.
//!
//! Nothing outside this module talks to the generated code directly: the rest
//! of the crate goes through the safe wrappers in [`super::sys`].

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/toupcam_bindings.rs"));

/// The event numbers this crate reasons about are written out longhand in
/// `crate::events` so that module can be compiled and tested without the SDK.
/// Check them against the header: if a future SDK renumbers anything, the
/// build fails here rather than the application mistaking a disconnect for a
/// white-balance change at 3am on a mountain.
const _: () = {
    assert!(crate::events::EVENT_IMAGE == TOUPCAM_EVENT_IMAGE as u32);
    assert!(crate::events::EVENT_STILLIMAGE == TOUPCAM_EVENT_STILLIMAGE as u32);
    assert!(crate::events::EVENT_ERROR == TOUPCAM_EVENT_ERROR as u32);
    assert!(crate::events::EVENT_DISCONNECTED == TOUPCAM_EVENT_DISCONNECTED as u32);
    assert!(crate::events::EVENT_NOFRAMETIMEOUT == TOUPCAM_EVENT_NOFRAMETIMEOUT as u32);
    assert!(crate::events::EVENT_NOPACKETTIMEOUT == TOUPCAM_EVENT_NOPACKETTIMEOUT as u32);
    assert!(crate::events::EVENT_TRIGGERFAIL == TOUPCAM_EVENT_TRIGGERFAIL as u32);
};

/// Convert a NUL-terminated wide string field into a `String`.
///
/// `wchar_t` is 32 bit on macOS and Linux and 16 bit on Windows; the generic
/// bound lets the same code serve both without naming the platform type.
pub fn from_wide<T: Copy + Into<i64>>(chars: &[T]) -> String {
    chars
        .iter()
        .map(|&c| c.into())
        .take_while(|&c| c != 0)
        .filter_map(|c| u32::try_from(c).ok().and_then(char::from_u32))
        .collect()
}

/// Read a NUL-terminated wide string from a pointer the SDK owns.
///
/// # Safety
/// `ptr` must be NUL-terminated and valid for reads, or null.
pub unsafe fn from_wide_ptr<T: Copy + Into<i64>>(ptr: *const T, max: usize) -> String {
    if ptr.is_null() {
        return String::new();
    }
    let slice = unsafe { std::slice::from_raw_parts(ptr, max) };
    from_wide(slice)
}

/// Build the NUL-terminated wide string the SDK expects for a camera id.
pub fn to_wide<T: From<u16>>(text: &str) -> Vec<T> {
    let mut wide: Vec<T> = text.encode_utf16().map(T::from).collect();
    wide.push(T::from(0u16));
    wide
}

/// Four-character code, as the SDK reports raw pixel formats.
pub const fn fourcc(code: &[u8; 4]) -> u32 {
    (code[0] as u32) | ((code[1] as u32) << 8) | ((code[2] as u32) << 16) | ((code[3] as u32) << 24)
}

pub const FOURCC_GBRG: u32 = fourcc(b"GBRG");
pub const FOURCC_GRBG: u32 = fourcc(b"GRBG");
pub const FOURCC_BGGR: u32 = fourcc(b"BGGR");
pub const FOURCC_RGGB: u32 = fourcc(b"RGGB");
