//! Raw bindings, generated by `build.rs` from the vendor `SVBCameraSDK.h`.
//!
//! Unlike the Touptek crate, the mock camera here is compiled against this
//! same real header, so the declarations these bindings are generated from
//! are always the vendor's own.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/svbony_bindings.rs"));

/// The error and control numbers this crate reasons about are written out
/// longhand in `crate::status` and `crate::controls` so those modules compile
/// and are tested without the SDK. Check them against the header: a vendor
/// renumbering should break the build, not the observing session.
const _: () = {
    assert!(crate::status::SVB_SUCCESS == SVB_ERROR_CODE_SVB_SUCCESS as i32);
    assert!(
        crate::status::SVB_ERROR_CAMERA_REMOVED == SVB_ERROR_CODE_SVB_ERROR_CAMERA_REMOVED as i32
    );
    assert!(crate::status::SVB_ERROR_TIMEOUT == SVB_ERROR_CODE_SVB_ERROR_TIMEOUT as i32);
    assert!(crate::status::SVB_ERROR_INVALID_SIZE == SVB_ERROR_CODE_SVB_ERROR_INVALID_SIZE as i32);
    assert!(
        crate::status::SVB_ERROR_CAMERA_CLOSED == SVB_ERROR_CODE_SVB_ERROR_CAMERA_CLOSED as i32
    );

    assert!(crate::controls::SVB_GAIN == SVB_CONTROL_TYPE_SVB_GAIN as i32);
    assert!(crate::controls::SVB_EXPOSURE == SVB_CONTROL_TYPE_SVB_EXPOSURE as i32);
    assert!(crate::controls::SVB_BLACK_LEVEL == SVB_CONTROL_TYPE_SVB_BLACK_LEVEL as i32);
    assert!(crate::controls::SVB_WB_R == SVB_CONTROL_TYPE_SVB_WB_R as i32);
    assert!(crate::controls::SVB_FRAME_SPEED_MODE == SVB_CONTROL_TYPE_SVB_FRAME_SPEED_MODE as i32);
    assert!(
        crate::controls::SVB_CURRENT_TEMPERATURE == SVB_CONTROL_TYPE_SVB_CURRENT_TEMPERATURE as i32
    );
};

/// Read a fixed-size C string field into a `String`.
pub fn c_string(bytes: &[::std::os::raw::c_char]) -> String {
    let bytes: Vec<u8> = bytes
        .iter()
        .map(|&c| c as u8)
        .take_while(|&c| c != 0)
        .collect();
    String::from_utf8_lossy(&bytes).trim().to_string()
}
